version: '3.6'
services:
  request:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/app'
    ports:
      - 5002:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/request_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/request_test
    depends_on:
        - db

  db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    ports:
      - 5106:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres