version: '3.6'
services:
  request:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/app'
    ports:
      - 5002:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/requestlenditdb_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/requestlenditdb_test
    depends_on:
        - db

  db:
    image: postgres:13.2-alpine
    ports:
      - 5106:5432
    volumes:
      - ./project/db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres