"""Migration database v2.0 schema

Revision ID: 61cd8752746f
Revises: 
Create Date: 2021-04-03 17:16:50.858940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "61cd8752746f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "request",
        "productcategoryid",
        existing_type=sa.SMALLINT(),
        nullable=True,
        existing_server_default=sa.text(
            "nextval('request_productcategoryid_seq'::regclass)"
        ),
    )
    op.drop_constraint("request_product_category_fk", "request", type_="foreignkey")
    op.create_foreign_key(
        None,
        "request",
        "product_category",
        ["productcategoryid"],
        ["productcategoryid"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "request", type_="foreignkey")
    op.create_foreign_key(
        "request_product_category_fk",
        "request",
        "product_category",
        ["productcategoryid"],
        ["productcategoryid"],
        onupdate="RESTRICT",
        ondelete="RESTRICT",
    )
    op.alter_column(
        "request",
        "productcategoryid",
        existing_type=sa.SMALLINT(),
        nullable=False,
        existing_server_default=sa.text(
            "nextval('request_productcategoryid_seq'::regclass)"
        ),
    )
    # ### end Alembic commands ###
